### ISSUE TITLE
Information request the result of each dataset in the benchmark

### ISSUE THREAD

**Issue by boranhan** [openai/mle-bench#16] opened 2024-10-24 17:35 UTC
Hello, thank you for your team's great work.

We are working on benchmarking different autoML algorithms. I'm wondering if you can provide the result (metrics or leadership ranking) for each individual dataset within the benchmark?

Thanks in advanced!

Boran

**Comment by thesofakillers** [comment] 2024-10-24 18:03
Duplicate of #9

**Closed** 2024-10-24 18:04 UTC
